Integration with Hibernate API
Tinkoff/neptune pull request #325
Opened 2022-03-15 07:11 UTC by Burnouttt

2022-03-16 10:31 UTC, TikhomirovSergey requested changes

2022-03-16 10:31 UTC, TikhomirovSergey commented on hibernate/src/main/java/ru/tinkoff/qa/neptune/hibernate/save/SaveStepSupplier.java
> +        checkArgument(isNotBlank(description), "Description should be defined");
https://sonarcloud.io/project/issues?resolved=false&severities=CRITICAL&pullRequest=325&id=neptune&open=AX-Nk5Ow25MySjKRsdyq

Если я в Spring сделал аналогично - приберусь при следуюзей "дизинсекции"

2022-03-16 10:31 UTC, TikhomirovSergey commented on hibernate/src/main/java/ru/tinkoff/qa/neptune/hibernate/delete/DeleteEntities.java
> +abstract class DeleteEntities<R, INPUT> implements Function<HibernateContext, Void> {
https://sonarcloud.io/project/issues?resolved=false&severities=MAJOR&pullRequest=325&id=neptune&open=AX-Nk5N625MySjKRsdx4

2022-03-16 12:34 UTC, TikhomirovSergey requested changes

2022-03-16 12:34 UTC, TikhomirovSergey commented on hibernate/src/main/resources/neptune_Localization_hibernate_ru_RU.properties
> +hibernate.delete.DeleteAllFromStepSupplier=\u0412\u0441\u0435 \u0437\u0430\u043F\u0438\u0441\u0438
Что-то не то с кодировкой

2022-04-14 15:00 UTC, TikhomirovSergey requested changes
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&pullRequest=325&id=neptune
Critical and major

2022-04-15 13:34 UTC, TikhomirovSergey approved these changes

2022-04-18 10:48 UTC, TikhomirovSergey requested changes

2022-04-18 10:48 UTC, TikhomirovSergey commented on hibernate/README.md
> +```xml
Инфа не актуальная , т.к. зависимости от hibernate у нас только для компиляции.
Зависимый проект должен подтянуть эту зависимость + hibernate

2022-04-18 10:48 UTC, TikhomirovSergey commented on hibernate/README.md
> +    dependencies {
смотри коммент выше

2022-04-18 10:48 UTC, TikhomirovSergey commented on hibernate/README.md
> +        api group: 'ru.tinkoff.qa.neptune', name: 'hibernate', version: LATEST_RELEASE_OR_BETA_VERSION
лучше testImplementation

2022-04-18 10:48 UTC, TikhomirovSergey commented on hibernate/README.md
> +            <version>${LATEST_RELEASE_OR_BETA_VERSION}</version>
<scope>test</test>

2022-04-18 10:48 UTC, TikhomirovSergey commented on hibernate/doc/rus/README.MD
> +<dependency>
Это нужно описать во внешнем ReadMe.MD

2022-04-18 10:48 UTC, TikhomirovSergey commented on hibernate/doc/rus/README.MD
> +api group: 'org.hibernate', name: 'hibernate-core', version: '5.6.0.Final'
коммент выше

2022-04-18 10:48 UTC, TikhomirovSergey commented on hibernate/doc/rus/README.MD
> +Hibernate OGM (пример артефакта для MongoDB):
Это обязательно подключать, что вынесено в отдельный заголовок?

2022-04-18 10:48 UTC, TikhomirovSergey commented on hibernate/doc/rus/README.MD
> +QueryDSL:
Это обязательно подключать, что вынесено в отдельный заголовок?

2022-04-19 10:20 UTC, Burnouttt commented on hibernate/doc/rus/README.MD
> +Hibernate OGM (пример артефакта для MongoDB):
обязательно

2022-04-19 10:20 UTC, Burnouttt commented on hibernate/doc/rus/README.MD
> +QueryDSL:
обязательно

2022-04-19 10:22 UTC, Burnouttt commented on hibernate/README.md
> +```xml
Про это же и написано в этой документации

2022-04-21 12:59 UTC, merged