Added the ability to receive clear messages
Tinkoff/neptune pull request #370
Opened 2022-09-13 08:59 UTC by AndrewCharykov

# Description

Added the ability to receive clear messages

Please select corresponding labels for this PR

## Type of change:

- [ ] Breaking change (changes that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] This change requires new tests
- [ ] This change requires correction of current tests

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have actualized tests to prove my changes are correct
- [ ] I have run existing tests to check that other functionality is working as expected
- [ ] I have marked code that should be removed `@Deprecated` (if there are breaking changes)
- [ ] I have removed only `@Deprecated` public code

2022-09-14 14:14 UTC, TikhomirovSergey requested changes

2022-09-14 14:14 UTC, TikhomirovSergey commented on rabbit.mq/src/main/java/ru/tinkoff/qa/neptune/rabbit/mq/function/get/RabbitMqBasicGetIterableSupplier.java
> +public abstract class RabbitMqBasicGetIterableSupplier<M, R, S extends RabbitMqBasicGetIterableSupplier<M, R, S>> extends
Нужно задепрекейтить весь класс

2022-09-14 14:21 UTC, TikhomirovSergey requested changes

2022-09-14 14:21 UTC, TikhomirovSergey commented on rabbit.mq/src/main/java/ru/tinkoff/qa/neptune/rabbit/mq/function/get/RabbitMqBasicGetSupplier.java
> +        return new RabbitMqBasicGetIterableItemSupplier.Mapped<>(new GetFromQueue(queue).andThen(new GetDeserializedData<>(typeT)), t -> t);
Метод должен быть задепрейкейчен

2022-09-14 14:21 UTC, TikhomirovSergey commented on rabbit.mq/src/main/java/ru/tinkoff/qa/neptune/rabbit/mq/function/get/RabbitMqBasicGetSupplier.java
> +    public static RabbitMqBasicGetIterableItemSupplier.Mapped<String, String> rabbitRawMessage(String queue, Charset charset) {
Метод должен быть задепрейкейчен

2022-09-14 14:21 UTC, TikhomirovSergey commented on rabbit.mq/src/main/java/ru/tinkoff/qa/neptune/rabbit/mq/function/get/RabbitMqBasicGetSupplier.java
> +    public static RabbitMqBasicGetIterableItemSupplier.Mapped<String, String> rabbitRawMessage() {
Метод должен быть задепрейкейчен

2022-09-16 16:16 UTC, TikhomirovSergey requested changes

2022-09-16 16:16 UTC, TikhomirovSergey commented on rabbit.mq/src/main/java/ru/tinkoff/qa/neptune/rabbit/mq/function/get/GetResponseSupplier.java
> +    public static GetResponseSupplier response(String queue) {
responses ?

2022-09-16 16:16 UTC, TikhomirovSergey commented on rabbit.mq/src/main/java/ru/tinkoff/qa/neptune/rabbit/mq/function/get/GetResponseSupplier.java
> +    @Description("Rabbit response")
"Rabbit responses"

2022-09-16 16:16 UTC, TikhomirovSergey commented on rabbit.mq/src/main/java/ru/tinkoff/qa/neptune/rabbit/mq/function/get/RabbitMqBasicGetArrayItemSupplier.java
> +    public final static class StringMessages extends RabbitMqBasicGetArrayItemSupplier<String, String, RabbitMqBasicGetArrayItemSupplier.StringMessages> {
Класс не используется
Его надо удалить или заюзать и покрыть использование тесто

2022-09-16 16:16 UTC, TikhomirovSergey commented on rabbit.mq/src/main/java/ru/tinkoff/qa/neptune/rabbit/mq/function/get/RabbitMqBasicGetIterableItemSupplier.java
> +    public final static class StringMessage extends RabbitMqBasicGetIterableItemSupplier<String, String, StringMessage> {
Класс не используется
Удалить или покрыть тестом

2022-09-20 10:49 UTC, TikhomirovSergey commented on rabbit.mq/src/main/java/ru/tinkoff/qa/neptune/rabbit/mq/function/get/GetFromQueue.java
> +    public List<String> getMessages() {
👍

2022-09-20 11:45 UTC, TikhomirovSergey approved these changes

2022-09-20 11:45 UTC, TikhomirovSergey commented on rabbit.mq/src/main/java/ru/tinkoff/qa/neptune/rabbit/mq/function/get/RabbitMqBasicGetIterableItemSupplier.java
>      }
Вернуть 
```java 
     public final static class StringMessage extends RabbitMqBasicGetIterableItemSupplier<String, String, StringMessage> {

        protected StringMessage(GetFromQueue.MergeProperty<List<String>> getFromQueue) {
            super(getFromQueue, s -> s);
            withDataTransformer(new StringDataTransformer());
        }
    }
```

Добавить статические методы для вызова

2022-09-20 11:45 UTC, TikhomirovSergey commented on rabbit.mq/src/main/java/ru/tinkoff/qa/neptune/rabbit/mq/function/get/RabbitMqBasicGetSupplier.java
>      @Description("Message body")
Убрать аннотацию

2022-09-20 11:45 UTC, TikhomirovSergey commented on rabbit.mq/src/main/java/ru/tinkoff/qa/neptune/rabbit/mq/function/get/RabbitMqBasicGetArraySupplier.java
> +    public static StringMessages rabbitArrayOfRawMessages(String queue) {
Убрать этот метод

2022-09-20 11:45 UTC, TikhomirovSergey commented on rabbit.mq/src/main/java/ru/tinkoff/qa/neptune/rabbit/mq/function/get/RabbitMqBasicGetArraySupplier.java
> +    public static StringMessages rabbitArrayOfRawMessages() {
Убрать этот метод

2022-09-20 11:45 UTC, TikhomirovSergey commented on rabbit.mq/src/main/java/ru/tinkoff/qa/neptune/rabbit/mq/function/get/RabbitMqBasicGetArraySupplier.java
> +    public final static class StringMessages extends RabbitMqBasicGetArraySupplier<String, String, StringMessages> {
убрать класс

2022-09-20 11:45 UTC, TikhomirovSergey commented on rabbit.mq/src/main/java/ru/tinkoff/qa/neptune/rabbit/mq/function/get/RabbitMqBasicGetListFromResponseSupplier.java
> +}
Вертуть 

```java
     public final static class StringMessages extends RabbitMqBasicGetIterableSupplier<String, String, StringMessages> {
        private StringMessages(GetFromQueue.MergeProperty<List<String>> getFromQueue) {
            super(getFromQueue, s -> s);
            withDataTransformer(new StringDataTransformer());
        }
    }
```

и добавить статические методы для его вызова

2022-09-20 13:10 UTC, AndrewCharykov commented on rabbit.mq/src/main/java/ru/tinkoff/qa/neptune/rabbit/mq/function/get/RabbitMqBasicGetArraySupplier.java
> +    public static StringMessages rabbitArrayOfRawMessages() {
Договорились оставить, чтоы было как в Кафке

2022-09-21 14:40 UTC, TikhomirovSergey approved these changes

2022-09-21 14:40 UTC, merged